### ISSUE TITLE
I don't seem able to enable the "trace" feature

### ISSUE THREAD

**Issue by bbigras** [dalance/nom-tracable#1]
```toml
[dependencies]
nom-tracable = { git = "https://github.com/dalance/nom-tracable.git", features = ["trace"] }
```

I use this but I don't have any output. Am I missing something?

```
parser | histogram                                          | count
------ | -------------------------------------------------- | -----


parser | cumulative histogram                               | count
------ | -------------------------------------------------- | -----
```

I'm able to run the example in your git repo with `cargo run --manifest-path=nom-tracable/Cargo.toml --example example --features trace`.

**Comment by dalance** [comment]
Sorry. I missed this issue.
The dependencies seems to be correct.
Did you add `#[tracable_parser]` to your parser?

**Comment by bbigras** [comment]
> Sorry. I missed this issue.

No worries. Thanks for the reply.

> Did you add #[tracable_parser] to your parser?

Yes. I have a minimal exemple. I'm probably doing something wrong.


```toml
[dependencies]
nom = "5.0"
nom-tracable = { git = "https://github.com/dalance/nom-tracable.git", features = ["trace"] }
nom_locate = "1.0.0"
```

```rust
use nom::bytes::complete::tag;
use nom::character::complete::digit1;
use nom::IResult;
use nom_locate::LocatedSpanEx;
use nom_tracable::{cumulative_histogram, histogram, tracable_parser, TracableInfo};

use std::io::Error;

type Span<'a> = LocatedSpanEx<&'a str, TracableInfo>;

#[tracable_parser]
pub fn parse(i: Span) -> IResult<Span, i32> {
    let (rest, _) = tag("test")(i)?;
    let (rest1, number) = digit1(rest)?;

    let number: i32 = number
        .fragment
        .parse()
        .map_err(|_e| nom::Err::Error((i, nom::error::ErrorKind::ParseTo)))?;

    Ok((rest1, number))
}

#[test]
fn test() -> Result<(), std::io::Error> {
    let info = TracableInfo::new().parser_width(64).fold("term");
    let (_rest, parsed) = parse(LocatedSpanEx::new_extra("test123", info)).unwrap();

    assert_eq!(parsed, 123);

    histogram();
    cumulative_histogram();

    assert!(false);

    Ok(())
}
```

```
❯ cargo test
   Compiling test-nom-trace v0.1.0 (/home/bbigras2/tmp/test-nom-trace)
[...]
    Finished dev [unoptimized + debuginfo] target(s) in 0.85s
     Running target/debug/deps/test_nom_trace-f4dcbabc0ed242d8

running 1 test
test test ... FAILED

failures:

---- test stdout ----

parser | histogram                                          | count
------ | -------------------------------------------------- | -----


parser | cumulative histogram                               | count
------ | -------------------------------------------------- | -----

thread 'test' panicked at 'assertion failed: false', src/lib.rs:34:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by dalance** [comment]
This is documentation mistake.
`trace` feature must be included in the crate using nom-tracable.
Please try the following `Cargo.toml` and do `cargo test --features trace`.

```toml
[features]
default = []
trace   = ["nom-tracable/trace"]

[dependencies]
nom = "5.0"
nom-tracable = { git = "https://github.com/dalance/nom-tracable.git" }
nom_locate = "1.0.0"
```
